const blogPosts = [
  {
    id: 1,
    img: "/img/blog/blog1.jpg",
    title: "This book is Link treatise on",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 2,
    img: "/img/blog/blog2.jpg",
    title: "The standard chunk of Lorem",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 3,
    img: "/img/blog/blog3.jpg",
    title: "Repeat predefined chunks",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 4,
    img: "/img/blog/blog4.jpg",
    title: "It is Link long established fact that",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 5,
    img: "/img/blog/blog5.jpg",
    title: "All the lorem ipsum generators",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 6,
    img: "/img/blog/blog6.jpg",
    title: "Lorem ipsum which looks",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 7,
    img: "/img/blog/blog7.jpg",
    title: "Various versions have evolved over",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 8,
    img: "/img/blog/blog8.jpg",
    title: "Various versions have evolved over",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
  {
    id: 9,
    img: "/img/blog/blog1.jpg",
    title: "Various versions have evolved over",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. ...",
    date: "02",
    month: "Jan",
    year: "2025",
  },
];

export default blogPosts;
