// const products = [
//   {
//     id: 1,
//     category: "Wireless earbuds", // must match categories.title
//     img1: "/img/product/home1-pro-1.jpg",
//     img2: "/img/product/home1-pro-2.jpg",
//     subtitle: "Wireless device",
//     title: "Wireless headphones",
//     newPrice: "৳520",
//     oldPrice: "৳3,000",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "20%",
//     brand: "Electon",
//   },
//   {
//     id: 2,
//     category: "Portable speaker",
//     img1: "/img/product/home1-pro-3.jpg",
//     img2: "/img/product/home1-pro-4.jpg",
//     subtitle: "Waterproof",
//     title: "Wireless mouse",
//     newPrice: "৳2,160",
//     oldPrice: "৳2,880",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "14%",
//     brand: "AudioMax",
//   },
//   {
//     id: 3,
//     category: "Air conditioner",
//     img1: "/img/product/home1-pro-5.jpg",
//     img2: "/img/product/home1-pro-6.jpg",
//     subtitle: "Live program",
//     title: "Pen drivess",
//     newPrice: "৳1,200",
//     oldPrice: "৳1,800",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "22%",
//     brand: "CoolAir",
//   },
//   {
//     id: 4,
//     category: "Ev charging plug",
//     img1: "/img/product/home1-pro-7.jpg",
//     img2: "/img/product/home1-pro-8.jpg",
//     subtitle: "Waterproof watch",
//     title: "Smart watch",
//     newPrice: "৳3,840",
//     oldPrice: "৳4,560",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "30%",
//     brand: "VoltPro",
//   },
//   {
//     id: 5,
//     category: "DVD player slot",
//     img1: "/img/product/home1-pro-1.jpg",
//     img2: "/img/product/home1-pro-2.jpg",
//     subtitle: "Wireless device",
//     title: "Wireless headphones",
//     newPrice: "৳2,520",
//     oldPrice: "৳3,000",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "20%",
//     brand: "Electon",
//   },
//   {
//     id: 6,
//     category: "360 camera",
//     img1: "/img/product/home1-pro-3.jpg",
//     img2: "/img/product/home1-pro-4.jpg",
//     subtitle: "Waterproof",
//     title: "Wireless mouse",
//     newPrice: "৳2,160",
//     oldPrice: "৳2,880",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "14%",
//     brand: "Vision360",
//   },
//   {
//     id: 7,
//     category: "Wireless earbuds",
//     img1: "/img/product/home1-pro-5.jpg",
//     img2: "/img/product/home1-pro-6.jpg",
//     subtitle: "Live program",
//     title: "Pen drivess",
//     newPrice: "৳1,200",
//     oldPrice: "৳1,800",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "22%",
//     brand: "Electon",
//   },
//   {
//     id: 8,
//     category: "Portable speaker",
//     img1: "/img/product/home1-pro-7.jpg",
//     img2: "/img/product/home1-pro-8.jpg",
//     subtitle: "Waterproof watch",
//     title: "Smart watch",
//     newPrice: "৳3,840",
//     oldPrice: "৳4,560",
//     description:
//       "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
//     rating: 5,
//     sale: "30%",
//     brand: "AudioMax",
//   },
// ];

// export default products;

const products = [
  {
    id: 1,
    category: "Wireless earbuds",
    img1: "/img/product/home1-pro-1.jpg",
    img2: "/img/product/home1-pro-2.jpg",
    images: [
      "/img/product/home1-pro-1.jpg",
      "/img/product/home1-pro-2.jpg",
      "/img/product/home1-pro-5.jpg",
      "/img/product/home1-pro-6.jpg",
      "/img/product/home1-pro-1.jpg",
      "/img/product/home1-pro-2.jpg",
      "/img/product/home1-pro-5.jpg",
      "/img/product/home1-pro-6.jpg",
    ],
    subtitle: "Wireless device",
    title: "Wireless headphones",
    newPrice: "৳520",
    oldPrice: "৳3,000",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "20%",
    brand: "Electon",
  },
  {
    id: 2,
    category: "Portable speaker",
    img1: "/img/product/home1-pro-3.jpg",
    img2: "/img/product/home1-pro-4.jpg",
    images: [
      "/img/product/home1-pro-3.jpg",
      "/img/product/home1-pro-4.jpg",
      "/img/product/home1-pro-7.jpg",
      "/img/product/home1-pro-8.jpg",
    ],
    subtitle: "Waterproof",
    title: "Wireless mouse",
    newPrice: "৳2,160",
    oldPrice: "৳2,880",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "14%",
    brand: "AudioMax",
  },
  {
    id: 3,
    category: "Air conditioner",
    img1: "/img/product/home1-pro-5.jpg",
    img2: "/img/product/home1-pro-6.jpg",
    subtitle: "Live program",
    title: "Pen drivess",
    newPrice: "৳1,200",
    oldPrice: "৳1,800",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "22%",
    brand: "CoolAir",
  },
  {
    id: 4,
    category: "Ev charging plug",
    img1: "/img/product/home1-pro-7.jpg",
    img2: "/img/product/home1-pro-8.jpg",
    subtitle: "Waterproof watch",
    title: "Smart watch",
    newPrice: "৳3,840",
    oldPrice: "৳4,560",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "30%",
    brand: "VoltPro",
  },
  {
    id: 5,
    category: "DVD player slot",
    img1: "/img/product/home1-pro-1.jpg",
    img2: "/img/product/home1-pro-2.jpg",
    subtitle: "Wireless device",
    title: "Wireless headphones",
    newPrice: "৳2,520",
    oldPrice: "৳3,000",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "20%",
    brand: "Electon",
  },
  {
    id: 6,
    category: "360 camera",
    img1: "/img/product/home1-pro-3.jpg",
    img2: "/img/product/home1-pro-4.jpg",
    subtitle: "Waterproof",
    title: "Wireless mouse",
    newPrice: "৳2,160",
    oldPrice: "৳2,880",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "14%",
    brand: "Vision360",
  },
  {
    id: 7,
    category: "Wireless earbuds",
    img1: "/img/product/home1-pro-5.jpg",
    img2: "/img/product/home1-pro-6.jpg",
    subtitle: "Live program",
    title: "Pen drivess",
    newPrice: "৳1,200",
    oldPrice: "৳1,800",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "22%",
    brand: "Electon",
  },
  {
    id: 8,
    category: "Portable speaker",
    img1: "/img/product/home1-pro-7.jpg",
    img2: "/img/product/home1-pro-8.jpg",
    subtitle: "Waterproof watch",
    title: "Smart watch",
    newPrice: "৳3,840",
    oldPrice: "৳4,560",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
    rating: 5,
    sale: "30%",
    brand: "AudioMax",
  },
];

export default products;
